import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TanstackProvider from '@/providers/tanstack-providers';
import { ProvidersContext } from '@/supports/context/user-context';
import { ProtectedRoute } from '@/supports/core/protected-route';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProvidersContext>
      <html lang='en'>
        <body className={inter.className}>
          <TanstackProvider>
            <ProtectedRoute>{children}</ProtectedRoute>
          </TanstackProvider>
        </body>
      </html>
    </ProvidersContext>
  );
}
